-- ============================================
-- Logback DBAppender Schema for H2
-- ============================================
-- Reference: https://logback.qos.ch/manual/appenders.html#DBAppender

-- 로그 이벤트 메인 테이블
CREATE TABLE IF NOT EXISTS LOGGING_EVENT (
    TIMESTMP BIGINT NOT NULL,
    FORMATTED_MESSAGE CLOB NOT NULL,
    LOGGER_NAME VARCHAR(256) NOT NULL,
    LEVEL_STRING VARCHAR(256) NOT NULL,
    THREAD_NAME VARCHAR(256),
    REFERENCE_FLAG SMALLINT,
    ARG0 VARCHAR(256),
    ARG1 VARCHAR(256),
    ARG2 VARCHAR(256),
    ARG3 VARCHAR(256),
    CALLER_FILENAME VARCHAR(256),
    CALLER_CLASS VARCHAR(256),
    CALLER_METHOD VARCHAR(256),
    CALLER_LINE CHAR(4),
    EVENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY
);

-- MDC 속성 테이블 (traceId 등)
CREATE TABLE IF NOT EXISTS LOGGING_EVENT_PROPERTY (
    EVENT_ID BIGINT NOT NULL,
    MAPPED_KEY VARCHAR(256) NOT NULL,
    MAPPED_VALUE CLOB,
    PRIMARY KEY (EVENT_ID, MAPPED_KEY),
    FOREIGN KEY (EVENT_ID) REFERENCES LOGGING_EVENT(EVENT_ID) ON DELETE CASCADE
);

-- 예외 스택트레이스 테이블
CREATE TABLE IF NOT EXISTS LOGGING_EVENT_EXCEPTION (
    EVENT_ID BIGINT NOT NULL,
    I SMALLINT NOT NULL,
    TRACE_LINE VARCHAR(2048) NOT NULL,
    PRIMARY KEY (EVENT_ID, I),
    FOREIGN KEY (EVENT_ID) REFERENCES LOGGING_EVENT(EVENT_ID) ON DELETE CASCADE
);

-- 조회 성능을 위한 인덱스
CREATE INDEX IF NOT EXISTS IDX_LOGGING_EVENT_TIMESTMP ON LOGGING_EVENT(TIMESTMP);
CREATE INDEX IF NOT EXISTS IDX_LOGGING_EVENT_LEVEL ON LOGGING_EVENT(LEVEL_STRING);
CREATE INDEX IF NOT EXISTS IDX_LOGGING_EVENT_LOGGER ON LOGGING_EVENT(LOGGER_NAME);

-- 로그 자동 정리 트리거 (7일 보관)
CREATE TRIGGER IF NOT EXISTS TRG_LOGGING_EVENT_CLEANUP
AFTER INSERT ON LOGGING_EVENT
FOR EACH ROW
CALL "com.example.admin_demo.global.log.H2LogCleanupTrigger";
